# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# try again

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: HelloWorld
  displayName: Hello World
  jobs:
  - job: HelloWorld
    displayName: Hello World
    steps:
    - script: |
        echo 'Hello World'

- stage: tf
  jobs:
  - job: tf
    displayName: tf
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '1.10.5'

      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: k21-devops
          backendAzureRmStorageAccountName: k21devops
          backendAzureRmContainerName: azure-devops
          backendAzureRmKey: terraform/terraform.tfstate
          backendAzureRmResourceGroupName: k21

      - script: |
          terraform --version

      - script: |
          cd terraform
          terraform validate

      - script:
          cd terraform
          terraform init
          terraform plan
# - stage: Validate
#   displayName: TF validate
#   jobs:
#   - job: TfValidate
#     displayName: TF validate
#     steps:
#     - task: TerraformInstaller@0
#       inputs:
#         terraformVersion: latest
    
#     - script: |
#         terraform --version
