variables:
- name: doDestroy
  value: false
- name: storageAccountName
  value: k21devops
- name: color
  value: '\033[0;33m'

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  jobs:
  - job: Terraform
    displayName: Terraform
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: $(TERRAFORM_VERSION)

      - task: TerraformTaskV4@4
        name: terraformInit
        displayName: Initialize terraform
        env:
          TF_LOG: INFO
        inputs:
          provider: azurerm
          command: init
          backendServiceArm: k21-devops
          backendAzureRmStorageAccountName: $(storageAccountName)
          backendAzureRmContainerName: tfstate
          backendAzureRmKey: 'terraform.tfstate'
          backendAzureRmResourceGroupName: k21
          workingDirectory: terraform

      - task: TerraformTaskV4@4
        name: terraformValidate
        displayName: Validate Terraform
        inputs:
          provider: azurerm
          command: validate
          workingDirectory: terraform

      - task: TerraformTaskV4@4
        name: terraformPlan
        displayName: Terraform Plan
        condition: eq(variables['doDestroy'], false)
        inputs:
          provider: azurerm
          command: plan
          commandOptions: '-out main.tfplan' #-var azure_tenant_id=$(AZURE_TENANT_ID) -var azure_subscription_id=$(AZURE_SUBSCRIPTION_ID)'
          environmentServiceNameAzureRM: k21-devops
          workingDirectory: terraform
 
      # Only runs if the 'terraformPlan' task has detected changes the in state. 
      - task: TerraformTaskV4@4
        name: terraformApply
        displayName: Terraform Apply
        condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'), eq(variables['doDestroy'], false))
        env:
          TF_LOG: INFO
        inputs:
          provider: azurerm
          command: apply
          commandOptions: main.tfplan
          environmentServiceNameAzureRM: k21-devops
          workingDirectory: terraform

      - task: TerraformTaskV4@4
        name: terraformPlanDestroy
        displayName: Terraform Plan for Destruction
        condition: eq(variables['doDestroy'], true)
        inputs:
          provider: azurerm
          command: plan
          commandOptions: '-destroy -out main.tfplan'
          environmentServiceNameAzureRM: k21-devops
          workingDirectory: terraform

      - task: TerraformTaskV4@4
        name: terraformDestroy
        displayName: Terraform Destroy
        condition: eq(variables['doDestroy'], true)        env:
          TF_LOG: INFO
        inputs:
          provider: azurerm
          command: destroy
          environmentServiceNameAzureRM: k21-devops
          workingDirectory: terraform

      # - script: | 
      #     ls terraform
      #     # echo $(storageAccountName)
      #     # az storage container list --account-name $(storageAccountName)
      #     # az storage blob list --account-name $(storageAccountName) --container-name k21devops
      #   name: state
      #   displayName: Terraform State

